version: '3.8'

services:
  backup_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    network_mode: host
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1